#!/bin/bash
option=$(echo -e "Quick\nSelect\nDisconnect\n" | dmenu -i -p "NORD VPN:")

case "$option" in
    Quick)
        nordvpn connect
    ;;
    Select)
	nordvpn countries | sed 's/[^a-zA-Z0-9_\t]//g' | tr '\t' '\n' | grep . | sort | dmenu -i -l 20 -p "Country: " | xargs -r nordvpn connect
    ;;
    Disconnect)
        nordvpn disconnect
    ;;
esac
